language: ruby
install: bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "Qd/qoU/hJpTaXCNYY/+dfT2PpJC0uMdtjU4knMt9YjbPhy8Gt5KaNOTiCljjcTVMyR8+XPsvSGYY2DpijmXg/Wwx85gQiOOu3QlTe1e/jLfT+pG9EmNKqqZUy0ptmOlp6BtYFdXkMH9AKw4jeCfbs6zBOaQPCP3Xi5Z/zjFCJjo="
