language: ruby
install: bundle install
script: bundle exec rake site:deploy
env:
  global:
    secure: "Zz4m/FESO+pBtK0hvlk3FpTdUTPEdTHcGzuT+CtOb4qrjRolvWtVtJmDqexp7duSosY7wk91Z9rX5eqUCoDB259yL0O7AVFmoqt95ymidfA9RJxIdRkOSGAv5rE2d8r3DUZuXbigm/6M8SuA1KvrI6A0CGNjx6JxQ2tK5Ffpyag="