permalink: /:categories/:year/:month/:day/:title

paginate: 10
paginate_path: "page:num"

exclude:
  - README.md
  - Rakefile
  - changelog.md
  - "*.Rmd"

pygments: true

title: Article-Level Metrics
name: ALM
description: Article-Level Metrics - Alternative Measures to Gauge the Impact of Research
tagline:
url: http://articlemetrics.github.io
authors:
 - name: Martin Fenner
   orcid: 0000-0003-1419-2405
   email: mfenner@plos.org
   gravatar: abfd3f212a9252ecb14687a2c62f934b
   github: mfenner
   twitter: mfenner
   description: Technical Lead PLOS Article-Level Metrics

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.

production_url:  http://articlemetrics.github.io
source_url:      http://github.com/articlemetrics/articlemetrics.github.io
archive_path:    archive.html
categories_path: categories.html
tags_path:       /tags.html
rss_path:        rss.xml
atom_path:       atom.xml

comments :
  provider : disqus
  disqus :
    short_name : articlemetrics

analytics :
    provider : google
    google :
        tracking_id :
