safe: true
lsi: false
pygments: true

relative_source: ../lagotto.github.io/
destination: ../lagotto.github.io-pages/

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: lagotto

permalink: pretty

paginate: 10
paginate_path: "blog/page:num"

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "strikethrough", "superscript", "autolink", "tables", "with_toc_data"]

title: Article-Level Metrics
name: ALM
description: Article-Level Metrics - Alternative Measures to Gauge the Impact of Research
tagline:
url: http://lagotto.github.io
authors:
 - name: Martin Fenner
   orcid: 0000-0003-1419-2405
   email: mfenner@plos.org
   gravatar: abfd3f212a9252ecb14687a2c62f934b
   github: mfenner
   twitter: mfenner
   description: Technical Lead PLOS Article-Level Metrics

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.

production_url:  http://lagotto.github.io
source_url:      http://github.com/lagotto/lagotto.github.io
tags_path:       /tags/
rss_path:        rss.xml
atom_path:       atom.xml

comments :
  provider : disqus
  disqus :
    short_name : lagotto

analytics :
    provider : google
    google :
        tracking_id :
